### ISSUE TITLE
Support for Display of Map specific information as map tile images

### ISSUE THREAD

**Issue by sudheesh001** [loklak/asksusi_com#7]

**Comment by daminisatya** [comment]
We dint want to make this complex instead we are giving them a link to the map.

**Comment by sudheesh001** [comment]
I believe the user should have minimal distractions to go away from the website that's there, from a user perspective we want engagement and the person to be available on the site for a very long time rather than bouncing on the pages front and back.

@mariobehling I think it's better to show an image tile, loklak supports it using the /vis/map.png API and it's better to have it there.

Clicking a tile should ask the user for their current location and then map to the given location. (enhancement for later)

**Comment by daminisatya** [comment]
#4

**Comment by mariobehling** [comment]
Regarding the chat style application, we should just follow existing chat clients and yes they are giving a chat window. Let's research if we can re-use an existing stack instead of having to implement everything ourselves. The feature of Susi is the AI behind it and we need to focus on this and we need more rules.
